language: node_js
node_js:
  - "stable"
install:
  - npm install
script:
  - npm run lint
  - npm test
  - npm run style
  - npm run build
  - node ./demo/demo1.js
  - node ./demo/demo2.js
  - node ./demo/demo3.js
  - node ./demo/demo4.js
  - node ./demo/demo5.js
  - node ./demo/demo6.js
  - node ./demo/demo7.js
  - node ./demo/demo8.js
  - node ./demo/demo9.js
  - node ./demo/demo10.js
  - node ./demo/demo11.js
  - node ./demo/demo12.js
after_failure:
  - "cat /home/travis/builds/dolanmiu/docx/npm-debug.log"
after_success:
  - npm run typedoc
  - echo "docx.js.org" > docs/.nojekyll
  - echo "docx.js.org" > docs/CNAME
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs
  on:
    branch: master
