name: Github Pages
on:
    push:
        branches:
            - master

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Install Dependencies
              run: npm ci --force
            - name: Build 🔧
              run: |
                  npm run typedoc
                  echo "docx.js.org" > docs/.nojekyll
                  echo "docx.js.org" > docs/CNAME
            - name: Archive Production Artifact
              uses: actions/upload-artifact@master
              with:
                  name: docs
                  path: docs
    deploy:
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo 🛎️
              uses: actions/checkout@master
            - name: Install Dependencies
              run: npm ci --force
            - name: Download Artifact
              uses: actions/download-artifact@master
              with:
                  name: docs
                  path: docs
            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@4.1.5
              with:
                  branch: gh-pages
                  folder: docs
